### ISSUE TITLE
Default app_label

### ISSUE THREAD

**Issue by khashashin** [Radi85/Comment#104]
**Environment**
* python version 3.8
* django Version 3.1
* django-comments-dab 2.0

**Describe the bug**
It would be very nice if I could give the default app label for `comments` attribute. Currently I'm struggling with incompatibility with drf-yasg package. I get issues since dab needs app label

```
[21/Nov/2020 20:42:03] "GET /api/swagger/ HTTP/1.1" 200 12423
[21/Nov/2020 20:42:04] "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
drf_yasg.inspectors.base WARNING  view's CommentCreate raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\rest_framework\generics.py", line 109, in get_serializer
    kwargs['context'] = self.get_serializer_context()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\api\views.py", line 24, in get_serializer_context
    self.validate(self.request)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 88, in validate
    self.app_name = self.validate_app_name(app_name)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 42, in validate_app_name
    raise CommentBadRequest(self.error)
comment.exceptions.CommentBadRequest: app name must be provided
drf_yasg.inspectors.base WARNING  view's CommentCreate raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\rest_framework\generics.py", line 109, in get_serializer
    kwargs['context'] = self.get_serializer_context()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\api\views.py", line 24, in get_serializer_context
    self.validate(self.request)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 88, in validate
    self.app_name = self.validate_app_name(app_name)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 42, in validate_app_name
    raise CommentBadRequest(self.error)
comment.exceptions.CommentBadRequest: app name must be provided
drf_yasg.inspectors.base WARNING  view's CommentCreate raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\rest_framework\generics.py", line 109, in get_serializer
    kwargs['context'] = self.get_serializer_context()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\api\views.py", line 24, in get_serializer_context
    self.validate(self.request)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 88, in validate
    self.app_name = self.validate_app_name(app_name)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 42, in validate_app_name
    raise CommentBadRequest(self.error)
comment.exceptions.CommentBadRequest: app name must be provided
drf_yasg.inspectors.base WARNING  view's CommentCreate raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\rest_framework\generics.py", line 109, in get_serializer
    kwargs['context'] = self.get_serializer_context()
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\api\views.py", line 24, in get_serializer_context
    self.validate(self.request)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 88, in validate
    self.app_name = self.validate_app_name(app_name)
  File "H:\GitHub\nohchi\nohchi_mott\server\.venv\lib\site-packages\comment\validators.py", line 42, in validate_app_name
    raise CommentBadRequest(self.error)
comment.exceptions.CommentBadRequest: app name must be provided
[21/Nov/2020 20:42:04] "GET /api/swagger/?format=openapi HTTP/1.1" 200 68170
```

**Expected behavior**
Add possibility to define default app label

**Comment by abhiabhi94** [comment]
I'm not sure I understand your query completely. What does default ` app label` mean?

`app_name` is required for `CommentList` view and not for `CommentCreate` view.

**Comment by khashashin** [comment]
Sorry, I'll explain. CommentList or Create requires `app_label` . Can we some how define default app_label during attribute definition or another way. As you see swagger is unable to work with comments and there is unfortunately no way to tell wich app_label is to use.

**Comment by abhiabhi94** [comment]
As much as I can recall, the `comment` app doesn't have anything that requires `app_label` as a parameter. Can you point out the specific case?

Have you associated the `comment` model with any of your object? `CommentList` requires an argument `app_name` which is the name of the django app that you have associated with the comment model.

**Comment by khashashin** [comment]
The error trace shows me that the error occurs in this line: https://github.com/Radi85/Comment/blob/df766a121bb7a0f8f8f572bf7e885123dc8ed235/comment/api/views.py#L28

I use comments as it is documented:

```
class CeWords(BaseModel):

    word = models.CharField(max_length=255, default="")

    plural_form = models.ManyToManyField('self', through='dosh.CePluralForm', through_fields=('singular', 'plural'))
    homonym = models.ManyToManyField('self', through='dosh.Homonym', through_fields=('homonym', 'word'))
    synonym = models.ManyToManyField('self', through='dosh.Synonym', through_fields=('synonym', 'word'))
    antonym = models.ManyToManyField('self', through='dosh.Antonym', through_fields=('antonym', 'word'))
    other_form = models.ManyToManyField('self', through='dosh.OtherForm', through_fields=('other_form', 'word'))

    # Fields to temporarily save the translation, after accepting
    # will be moved in to related models e.g RussianWord and EnglishWord
    temp_ru = models.TextField(default="", blank=True)
    temp_en = models.TextField(default="", blank=True)

    is_human = models.BooleanField(default=False)

    latin_version = models.CharField(max_length=255, default="", blank=True)

    uncensored_word = models.BooleanField(default=False)

    description = models.TextField(default="", blank=True)
    special_case_description = models.TextField(default="", blank=True)

    comments = GenericRelation(Comment)

    class Meta:
        indexes = [models.Index(fields=['word'])]

    def __str__(self):
        return self.word
```

Honestly I'm not quite sure why I get this issue, probably swagger(drf-yasg) trying to serialize Somehow commen Models and there it is triggered.

**Comment by Radi85** [comment]
As you can see in the [API documentation](https://django-comment-dab.readthedocs.io/Web%20API.html#comment-api-actions) the `app_name`, `model_name` and `model_id` are required query params in order to retirieve comments list or create a comment in a certain object.
This is the call for comments list:
```sh
$ curl '{{baseURL}}/api/comments/?model_name=MODEL_NAME&model_id=ID&app_name=APP_NAME' -H "Content-Type: application/json"
```
The error mentioned in your traceback is due to missing `app_name`, I am not sure how `drf-yasg` works but it might make a call aginst the url without providing the queries that I mentioned.

**Comment by khashashin** [comment]
Ok, I guess I have to somehow wrap the comment list and create views and handle the necessary parameters to tell 'drf-yasg' how to load these views. Thanks for your attention. You guys are doing a great job, thanks vm.
