### ISSUE TITLE
'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by YoungOmer** [Radi85/Comment#77]
**PiPenv**
* python==3.8
* django==3.1.1
* django-comments-dab

**Describe the bug**
Am getting an error saying "'NoneType' object has no attribute 'lower'" and the error is coming from "comment\utils.py, line 26, in get_model_obj"

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/50248944/93514645-4c9be480-f8dc-11ea-9ec8-37eaee2888cc.png)

**Comment by abhiabhi94** [comment]
Could you please show the template file that you're using to render comments? Also consider pasting the `traceback` of the error from the developer console.

**Comment by YoungOmer** [comment]
Traceback
Environment:


Request Method: GET
Request URL: http://localhost:8000/music/song/on-my-way/

Django Version: 3.1.1
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_countries',
 'django_cleanup',
 'ckeditor',
 'crispy_forms',
 'accounts',
 'comment',
 'contact',
 'events',
 'gossip',
 'music',
 'recents',
 'search']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template C:\Users\YoungOmer\Desktop\Development\csw\templates\base.html, error at line 0
   'NoneType' object has no attribute 'lower'
   1 : {% load static %}
   2 : <!DOCTYPE html>
   3 : <html lang="en">
   4 : 
   5 : <head>
   6 :     <meta charset="UTF-8">
   7 :     <meta name="description" content="">
   8 :     <meta http-equiv="X-UA-Compatible" content="IE=edge">
   9 :     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   10 : 


Traceback (most recent call last):
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\YoungOmer\.virtualenvs\csw-0_vsD1Z3\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\YoungOmer\Desktop\Development\csw\comment\templatetags\comment_tags.py", line 78, in render_comments
    context = get_comment_context_data(request, model_object=obj)
  File "C:\Users\YoungOmer\Desktop\Development\csw\comment\utils.py", line 84, in get_comment_context_data
    model_object = get_model_obj(app_name, model_name, model_id)
  File "C:\Users\YoungOmer\Desktop\Develop
ment\csw\comment\utils.py", line 26, in get_model_obj
    content_type = ContentType.objects.get(app_label=app_name, model=model_name.lower())

Exception Type: AttributeError at /music/song/on-my-way/
Exception Value: 'NoneType' object has no attribute 'lower'


## template
![Untitled1](https://user-images.githubusercontent.com/50248944/93595704-15294880-f96d-11ea-8e15-b80577952064.png)

**Comment by abhiabhi94** [comment]
For the template `render_comments` you have to pass the first argument as the instance of the model object that needs to display comments.

I'm not sure you have passed `obj` any value from the `view` function to the template which renders comments. For example on how to use them correctly, you may take a look at the [example](https://github.com/Radi85/Comment/tree/master/test/example) directory. 

Specifically, these portions might be helpful:

`DetailView`: https://github.com/Radi85/Comment/blob/master/test/example/post/views.py#L15
Template: https://github.com/Radi85/Comment/blob/master/test/example/templates/post/postdetail.html
